### ISSUE TITLE
Додати runtime модулі

### ISSUE THREAD

**Issue by denkisil** [dkostmii/mavka#3]
Runtime модуль - модуль, який імпортується під час інтерпретації і не потребує попереднього імпорту.

Щоб організувати його, я пропоную зробити це таким чином
- Додати теку `runtime_modules`, де знаходяться файли модулів і, можливо, певний скрипт для цього
- Під час інтепретації додавати ці всі модулі перед тим, як розглянути файл, який запускається

**Comment by dkostmii** [comment]
Приклад зроблено у комміті 255327a

**Comment by dkostmii** [comment]
Імперативний конструктор разом з прихованим декларативним конструктором реалізовано у комміті 2623ec716f160517ff47c1111a9f53be7bb0c1d3

**Comment by dkostmii** [comment]
Як згадано [ось тут](https://github.com/dkostmii/mavka/issues/2#issuecomment-1494258873), подальша дискусія відбуватиметься в основному репозиторії.
